site:
  title: "*DEVELOPMENT* Foggy Ubiquity *DEVELOPMENT*"
  # the 404 page and sitemap files only get generated when the url property is set
  url: http://localhost:5000/
  start_page: devsecops::index.adoc
content:
  sources:
  - url: ../xaas
    branches: HEAD
  - url: ../devsecops
    branches: HEAD
  - url: ../language
    branches: HEAD
ui:
  bundle:
    url: https://github.com/foggyubiquity/www-ui/releases/download/0.1.4/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental/lunr/supplemental_ui

