---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: heading
  label: Series
- type: directory
  path: pages/nixos
  label: NixOS
  create: all
  match: "**/*"
  templates:
  - page
- type: heading
  label: Globals
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _data/sidebars
  label: Sidebars
  create: documents
  match: "**/*"
  new_doc_ext: yml
upload_dir: foggyubiquity.com
public_path: https://res.cloudinary.com/tayloredtechnology/image/upload/c_scale,w_auto:100,dpr_auto
front_matter_path: https://res.cloudinary.com/tayloredtechnology/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
